--- #YAML:1.0
name:               Math-SymbolicX-FastEvaluator
version:            0.01
abstract:           Fast, XS, stack-based formula evaluator
author:
    - Steffen Mueller <smueller@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    aliased:         0.22
    Math::Symbolic:  0.510
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
